from pandasql import sqldf


class SQLEngine:

    def run(self, df, entities=None):
        """
        Executes SQL queries generated by the Query Planner / LLM.

        Parameters
        ----------
        df : pandas.DataFrame
            Dataset loaded by the user.

        entities : list
            Expected format:
            ["SELECT ... FROM df ..."]

        Returns
        -------
        list[dict] | dict
            Query results or error message.
        """

        if not entities:
            return {"error": "No SQL query provided."}

        sql_query = entities[0]

        if not isinstance(sql_query, str):
            return {"error": "Invalid SQL query format."}

        # Clean possible markdown formatting
        sql_query = (
            sql_query
            .replace("```sql", "")
            .replace("```", "")
            .strip()
        )

        # Ensure SQL starts with SELECT
        if not sql_query.lower().startswith("select"):
            return {
                "error": "Generated query must start with SELECT.",
                "query": sql_query
            }

        try:

            result = sqldf(sql_query, {"df": df})

            # Convert result dataframe → JSON style list
            if result is None or result.empty:
                return []

            return result.to_dict(orient="records")

        except Exception as e:

            return {
                "error": "SQL execution failed.",
                "details": str(e),
                "query": sql_query
            }